---
title: "0.1_color_palettes.Rmd"
author: "Shayna A. Sura"
date: "2024-07-13"
output: html_document
---

```{r setup, include=FALSE}







```


```{r}

  # scale_fill_paletteer_c("grDevices::PinkYl",
  #                        direction = -1,
  #                        limits = c(0,0.7)) +

```




```{r}

"#D9D2FC"

"#F74A64"


# Coral to deep purple
custom_colors <- colorRampPalette(c("navy", "#383bdd","purple", "#fcccfc", "hotpink")) 


custom_colors <- colorRampPalette(c("navy", "#383bdd","purple3", "sienna1", "hotpink"))

custom_colors <- colorRampPalette(c("#ffe7bc", "#ecc884", "#fdb17e", "#f6c9c9", "#f47e7e", "#db5d7c", "hotpink"))

custom_colors <- colorRampPalette(c("#ffe7bc", "#ecc884", "#fdb17e", "#f47e7e", "#db5d7c"))

custom_colors <- colorRampPalette(c("#ffe7bc", "#ecc884", "#fdb17e", "#f47e7e", "#f768a1")) 

custom_colors <- colorRampPalette(c("#ffe7bc", "#fdb17e", "#f47e7e", "#db5d7c"))

custom_colors <- colorRampPalette(c("#ffe7bc", "#f6c9c9", "#fdb17e",  "#f47e7e", "#db5d7c"))

custom_colors <- colorRampPalette(c("#ffe7bc", "#f6c9c9", "#f47e7e", "hotpink"))

custom_colors <- colorRampPalette(c("#ecc884", "#f6c9c9", "#f47e7e", "hotpink"))

custom_colors <- colorRampPalette(c("#05aba9", "#9ce5de", "#d9eedb", "#f6c9c9", "#f99192", "#f97171"))

custom_colors <- colorRampPalette(c("#e27c7c", "#a86464", "#6d4b4b", "#503f3f", "#333333", "#3c4e4b", "#466964", "#599e94", "#6cd4c5"))


custom_colors <- colorRampPalette(c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", 
                    "#9ecae1", "#c6dbef", "#deebf7", "#f7f7f7", "#fde0dd", 
                    "#fcc5c0", "#fa9fb5", "#f768a1", "#dd3497", "#ae017e", 
                    "#7a0177"))


custom_colors <- colorRampPalette(c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", 
                    "#9ecae1", "#c6dbef", "#deebf7", "#fde0dd", 
                    "#fcc5c0", "#fa9fb5", "#f768a1", "#dd3497", "#ae017e"))



custom_colors <- colorRampPalette(c("#08306b", "#08519c", "#2171b5", "#4292c6", "#6baed6", 
                                     "#9ecae1", "#c6dbef", "#deebf7", "#fcbba1", 
                                     "#fc9272", "#fa9fb5", "#f768a1", "#dd3497", "hotpink"))


custom_colors <- colorRampPalette(c("#ffe7bc", "#ecc884", "#fdb17e", "#f6c9c9", "#f47e7e", 
                                    "#db5d7c", "hotpink", "#05aba9", "#9ce5de", "#d9eedb", 
                                    "#f6c9c9", "#f99192", "#f97171", "#ffae03", "#f9d74c"))

custom_colors <- colorRampPalette(c("#ffe7bc", "#ecc884", "#f9d74c", "#fdb17e","#ffae03", "#f99192","#f768a1", "#f97171","#f6c9c9", "#f47e7e", 
                                       "#db5d7c",  
                                   "hotpink",))


custom_colors <- colorRampPalette(c("#ffe7bc", "#ecc884", "#fdb17e", "#f47e7e", "#f768a1")) 

"#FF7F50"


custom_colors <- colorRampPalette(c("#43015e", "#721a60", "#a13462", "#d04d64", "#ff6666")) 

custom_colors <- colorRampPalette(c("#ddebef", "#f3992f", "#e76a5b", "#cc215c", "#fd7f96")) 


coral_cover_palette <- c("#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c",
                         "#fc4e2a", "#e31a1c", "#bd0026", "#fcbba1", "#fc9272",
                         "#fb6a4a", "#ef3b2c", "#cb181d", "#a50f15", "#67000d")

coral_cover_palette <- c("#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c",
                         "#fc4e2a", "#e31a1c", "#bd0026", "#fcbba1", "#fc9272",
                         "#fb6a4a", "#ef3b2c", "#fdae6b", "#f16913", "#d94801")


custom_colors <- colorRampPalette(c("#08306b", "#2d00f7", "#6a00f4", "#8900f2", "#a100f2", "#b100e8", "#bc00dd", "#d100d1", "#db00b6", "#e500a4", "#f20089"))

custom_colors <- colorRampPalette(c("#f72585", "#b5179e", "#7209b7", "#560bad", "#480ca8", "#3a0ca3", "#3f37c9", "#4361ee", "#4895ef", "#4cc9f0"))


custom_colors <- colorRampPalette(c("#4cc9f0", "#4895ef", "#4361ee", "#3f37c9", "#3a0ca3", "#480ca8", "#560bad", "#7209b7", "#b5179e", "#f72585"))


custom_colors <- colorRampPalette(c("#3a0ca3", "#480ca8", "#560bad", "#7209b7", "#b5179e", "#f72585"))


custom_colors <- colorRampPalette(c("#FAE8B7", "#FAC8AF", "#F9A7A6", "#F9879E", "#F86696", "#F8468D", "#F72585"))


custom_colors <- colorRampPalette(c("#FAE8B7", "#FAC8AF", "#F9A7A6", "#F9879E", "#F86696", "#F8468D", "#F72585", "#b5179e", "#7209b7"))

```

