---
title: "resilience_model_test"
author: "Shayna A. Sura"
date: "2024-07-13"
output: html_document
---

```{r setup, include=FALSE}

library(deSolve)
library(reshape2)
library(viridis)
library(gridExtra)
library(tidyverse) # includes and loads the packages listed below
# library(readr)
# library(tidyr)
# library(dplyr)
# library(ggplot2)
# library(lubridate)

library(here) # helps with paths for files

```



# Our Model Set up

```{r Phase 2 Model}


#These were the initial conditions for the van de Leemput et al. (2016) basic model.
# H0<-0.9
# C0<-0.75
# M0<-0.1


# Initial Conditions - for 'collapsed' model
G0<-0.45
R0<-0
B0<-0.45
C0<-0.75
T0<-0.05
M0<-0.05
S0 <- 1 - T0 - C0 - M0


P2_state_vars<-c(GG=G0, RR=R0, BB=B0, CC=C0, TT=T0, MM=M0, SS=S0)

#generate a series of times at which you want the ODE solver to output population sizes
P2_tseq<-seq(0,1000,by=0.1)

#Generate a vector of parameter values - for 'collapsed' model
P2_pars<-c(bc<-0.3,
           bt<-0.8,      #use the same value as bm from basic model
           bm<-0.8,      #use the same value as bm from basic model
           ic<-0.05,
           it<-0.025,    #need two of these, one for turf and one for macroalgae
           im<-0.025,    #need two of these, one for turf and one for macroalgae
           dc<-0.1,
           r<-1,
           # gt<-1,       #need two of these, one for turf and one for macroalgae
           # gm<-1,       #need two of these, one for turf and one for macroalgae
           gt<-2,       #need two of these, one for turf and one for macroalgae
           gm<-2,       #need two of these, one for turf and one for macroalgae
           etaT<-1,     #need two of these, one for turf and one for macroalgae
           etaM<-1,     #need two of these, one for turf and one for macroalgae
           alphaT<-0.5,
           alphaM<-0.5,
           sigma<-0.6,
           f<-0.1,
           gamma<-0)


# Our Model Setup - for 'collapsed' model
P2_Model<-function(P2_tseq,P2_state_vars,P2_pars){
  GG <- P2_state_vars[1]
  RR <- P2_state_vars[2]
  BB <- P2_state_vars[3]
  CC <- P2_state_vars[4]
  TT <- P2_state_vars[5]
  MM <- P2_state_vars[6]
  SS <- 1 - CC - TT - MM
  
  bc <- P2_pars[1]
  bt <- P2_pars[2]
  bm <- P2_pars[3]
  ic <- P2_pars[4]
  it <- P2_pars[5]
  im <- P2_pars[6]
  dc <- P2_pars[7]
  r <- P2_pars[8]
  gt <- P2_pars[9]
  gm <- P2_pars[10]
  etaT <- P2_pars[11]
  etaM <- P2_pars[12]
  alphaT <- P2_pars[13]
  alphaM <- P2_pars[14]
  sigma <- P2_pars[15]
  f <- P2_pars[16]
  gamma <- P2_pars[17]
  
  dG_dt <-r*GG*(1 - ((GG+RR+BB) / ((1-sigma) + sigma*CC))) - f*GG
  dR_dt <-r*RR*(1 - ((GG+RR+BB) / ((1-sigma) + sigma*CC))) - f*RR
  dB_dt <-r*BB*(1 - ((GG+RR+BB) / ((1-sigma) + sigma*CC))) - f*BB
  dC_dt <- (ic + bc*CC)*SS*(1-(alphaT*TT+alphaM*MM)) - dc*CC
  dT_dt <- (it + bt*TT)*(SS) - (gamma*TT) - (((gt*GG*TT) / (gt*etaT*TT+1)) + ((gt*RR*TT)/(gt*etaT*TT+gm*etaM*MM+1)))
  dM_dt <- (im + bm*MM)*(SS) + (gamma*TT) - (((gm*BB*MM) / (gm*etaM*MM+1)) + ((gm*RR*MM)/(gt*etaT*TT+gm*etaM*MM+1)))


  return(list(c(dG <- dG_dt,
                dR <- dR_dt,
                dB <- dB_dt,
                dC <- dC_dt,
                dT <- dT_dt,
                dM <- dM_dt)))
}


```


## hh_pars   Parameter values actually used for expanded model

```{r}

#Generate a vector of parameter values - for our model
hh_pars<-c(bc<-0.3, bt<-0.8,bm<-0.5,      #expansion of current benthic cover
           ic<-0.05, it<-0.05, im<-0,     #import of propagules
           dc<-0.1,                       #coral mortality
           r<-1,                          #herbivore growth rate
           # gt<-1, gm<-0.5,                #algae mortality
           gt<-2, gm<-1,                #algae mortality
           etaT<-0, etaM<-1,              #algae handling time
           alphaT<-0.25, alphaM<-0.5,     #competitive effect on coral
           sigma<-0.6,                    #relationship between coral & herbivores
           f<-0.5,                        #fishing pressure
           gamma<-0.1)                    #transition from turf to macroalgae


```


## For loops over different initial coral cover for various levels of fishing pressure using the expanded model but with the more realistic parameters (hh_pars). The initial conditions are the same though.

```{r}

f_values<-seq(0,1,by=0.01)
coral_initials<-seq(0,0.85,0.01)

expanded_1<-expand.grid(coral_initials,f_values)
colnames(expanded_1)<-c("Initial_Coral","Fishing_Pressure")


for(i in 1:length(expanded_1$Initial_Coral)){
    C0<-expanded_1$Initial_Coral[i]
    B0<-0.3
    R0<-0.3
    G0<-0.3
#    C0<-0.75
    S0<-0.15
    M0<-(1-C0-S0)/2
    T0<-(1-C0-S0)/2
    hh_pars[16]<-expanded_1$Fishing_Pressure[i]   #set the fishing pressure
    zz_output<-lsoda(c(Grazers =G0, Generalists =R0, Browsers =B0,
                   Coral = C0,Turf = T0,Macroalgae=M0),
                 P2_tseq, P2_Model, hh_pars)
    zz_output_new<-as.data.frame(zz_output)
    expanded_1$Final_Coral[i]<-tail(zz_output_new$Coral,1)
}


# export clean bio data to csv file
write_csv(expanded_1, file = "../output/analyses/fig5/bistability-expanded_1.csv")


## Trying to figure out precisely which fishing pressure values the coral reef system exhibits bistability depending upon the initial coral cover conditions.
exp_C0_0<-subset(expanded_1,subset = expanded_1$Initial_Coral == 0)
exp_C0_0.85<-subset(expanded_1,subset = expanded_1$Initial_Coral == 0.85)

for(i in 1:nrow(exp_C0_0)){
  exp_C0_0$bistability[i]<-format(round(exp_C0_0[i,3], 7), nsmall = 7) != 
                     format(round(exp_C0_0.85[i,3], 7), nsmall = 7)
}


## Find the fishing pressure values where the system can exhibit bistability
min(exp_C0_0$Fishing_Pressure[which(exp_C0_0$bistability==TRUE)])
max(exp_C0_0$Fishing_Pressure[which(exp_C0_0$bistability==TRUE)])
exp_C0_0$Fishing_Pressure[which(exp_C0_0$bistability==TRUE)]
## bistability between 0.42 - 0.58


```



