---
title: "Supplemental Figure S10 - Browsers: Loss of Bistability"
author: "Shayna A. Sura"
date: "2024-07-13 - July 13, 2024"
output: html_document
---



```{r setup, include=FALSE}

library(deSolve)
library(reshape2)
library(viridis)
library(gridExtra)
library(tidyverse) # includes and loads the packages listed below
# library(readr)
# library(tidyr)
# library(dplyr)
# library(ggplot2)
# library(lubridate)

library(here) # helps with paths for files

library(purrr)
library(future)
library(furrr)

library(scales)

```



# Our Model Set up

```{r Phase 2 Model}


#These were the initial conditions for the van de Leemput et al. (2016) basic model.
# H0<-0.9
# C0<-0.75
# M0<-0.1


# Initial Conditions - for 'collapsed' model
G0<-0.45
R0<-0
B0<-0.45
C0<-0.75
T0<-0.05
M0<-0.05
S0 <- 1 - T0 - C0 - M0


P2_state_vars<-c(GG=G0, RR=R0, BB=B0, CC=C0, TT=T0, MM=M0, SS=S0)

#generate a series of times at which you want the ODE solver to output population sizes
P2_tseq<-seq(0,1000,by=0.1)

#Generate a vector of parameter values - for 'collapsed' model
P2_pars<-c(bc<-0.3,
           bt<-0.8,      #use the same value as bm from basic model
           bm<-0.8,      #use the same value as bm from basic model
           ic<-0.05,
           it<-0.025,    #need two of these, one for turf and one for macroalgae
           im<-0.025,    #need two of these, one for turf and one for macroalgae
           dc<-0.1,
           r<-1,
           # gt<-1,       #need two of these, one for turf and one for macroalgae
           # gm<-1,       #need two of these, one for turf and one for macroalgae
           gt<-2,       #need two of these, one for turf and one for macroalgae
           gm<-2,       #need two of these, one for turf and one for macroalgae
           etaT<-1,     #need two of these, one for turf and one for macroalgae
           etaM<-1,     #need two of these, one for turf and one for macroalgae
           alphaT<-0.5,
           alphaM<-0.5,
           sigma<-0.6,
           f<-0.1,
           gamma<-0)


# Our Model Setup - for 'collapsed' model
P2_Model<-function(P2_tseq,P2_state_vars,P2_pars){
  GG <- P2_state_vars[1]
  RR <- P2_state_vars[2]
  BB <- P2_state_vars[3]
  CC <- P2_state_vars[4]
  TT <- P2_state_vars[5]
  MM <- P2_state_vars[6]
  SS <- 1 - CC - TT - MM
  
  bc <- P2_pars[1]
  bt <- P2_pars[2]
  bm <- P2_pars[3]
  ic <- P2_pars[4]
  it <- P2_pars[5]
  im <- P2_pars[6]
  dc <- P2_pars[7]
  r <- P2_pars[8]
  gt <- P2_pars[9]
  gm <- P2_pars[10]
  etaT <- P2_pars[11]
  etaM <- P2_pars[12]
  alphaT <- P2_pars[13]
  alphaM <- P2_pars[14]
  sigma <- P2_pars[15]
  f <- P2_pars[16]
  gamma <- P2_pars[17]
  
  dG_dt <-r*GG*(1 - ((GG+RR+BB) / ((1-sigma) + sigma*CC))) - f*GG
  dR_dt <-r*RR*(1 - ((GG+RR+BB) / ((1-sigma) + sigma*CC))) - f*RR
  dB_dt <-r*BB*(1 - ((GG+RR+BB) / ((1-sigma) + sigma*CC))) - f*BB
  dC_dt <- (ic + bc*CC)*SS*(1-(alphaT*TT+alphaM*MM)) - dc*CC
  dT_dt <- (it + bt*TT)*(SS) - (gamma*TT) - (((gt*GG*TT) / (gt*etaT*TT+1)) + ((gt*RR*TT)/(gt*etaT*TT+gm*etaM*MM+1)))
  dM_dt <- (im + bm*MM)*(SS) + (gamma*TT) - (((gm*BB*MM) / (gm*etaM*MM+1)) + ((gm*RR*MM)/(gt*etaT*TT+gm*etaM*MM+1)))


  return(list(c(dG <- dG_dt,
                dR <- dR_dt,
                dB <- dB_dt,
                dC <- dC_dt,
                dT <- dT_dt,
                dM <- dM_dt)))
}


```


## hh_pars   Parameter values actually used for expanded model

```{r}

#Generate a vector of parameter values - for our model
hh_pars<-c(bc<-0.3, bt<-0.8,bm<-0.5,      #expansion of current benthic cover
           ic<-0.05, it<-0.05, im<-0,     #import of propagules
           dc<-0.1,                       #coral mortality
           r<-1,                          #herbivore growth rate
           # gt<-1, gm<-0.5,                #algae mortality
           gt<-2, gm<-1,                #algae mortality
           etaT<-0, etaM<-1,              #algae handling time
           alphaT<-0.25, alphaM<-0.5,     #competitive effect on coral
           sigma<-0.6,                    #relationship between coral & herbivores
           f<-0.5,                        #fishing pressure
           gamma<-0.1)                    #transition from turf to macroalgae


```


### Bistability Analyses - Browser-Dominated Scenarios
Is there an initial abundance/condition for browsers that allows bistability to disappear completely?

```{r}


plan(multisession)  # Use plan(multicore) for Unix-based systems

P2_tseq <- seq(0, 1000, by = 0.1)

# Different B0 conditions
B0_conditions <- c(0.7, 0.65, 0.66, 0.67, 0.68, 0.69, 0.75)

f_values <- seq(0, 1, by = 0.01)
coral_initials <- seq(0, 0.85, 0.01)

run_model <- function(initial_coral, fishing_pressure, B0, R0, G0) {
  C0 <- initial_coral
  S0 <- 0.15
  M0 <- (1 - C0 - S0) / 2
  T0 <- (1 - C0 - S0) / 2
  
  # Update fishing pressure in parameters
  hh_pars[16] <- fishing_pressure
  
  # Run the model
  zz_output <- lsoda(c(Grazers = G0, Generalists = R0, Browsers = B0, Coral = C0, Turf = T0, Macroalgae = M0),
                     P2_tseq, P2_Model, hh_pars)
  
  # Extract the final coral value
  final_coral <- tail(as.data.frame(zz_output)$Coral, 1)
  return(final_coral)
}

results_list <- list()

for (B0 in B0_conditions) {
  if (B0 == 0.7) {
    R0 <- 0.10
    G0 <- 0.10
  } else if (B0 == 0.65) {
    R0 <- 0.125
    G0 <- 0.125
  } else if (B0 == 0.66) {
    R0 <- 0.12
    G0 <- 0.12
  } else if (B0 == 0.67) {
    R0 <- 0.115
    G0 <- 0.115
  } else if (B0 == 0.68) {
    R0 <- 0.11
    G0 <- 0.11
  } else if (B0 == 0.69) {
    R0 <- 0.105
    G0 <- 0.105
  } else if (B0 == 0.75) {
    R0 <- 0.075
    G0 <- 0.075
  }

  high_browsers <- expand.grid(Initial_Coral = coral_initials, Fishing_Pressure = f_values)
  
  high_browsers <- high_browsers %>%
    mutate(Final_Coral = future_pmap_dbl(list(Initial_Coral, Fishing_Pressure), run_model, B0 = B0, R0 = R0, G0 = G0))
  
  high_browsers <- high_browsers %>%
    mutate(Browsers = B0)
  
  results_list[[paste0("B0_", B0)]] <- high_browsers
}

final_results <- bind_rows(results_list)
final_results


# Add Id column and convert it to factor with specified levels
final_results <- final_results %>%
  mutate(Id = factor(paste0("B0 = ", Browsers), 
                     levels = paste0("B0 = ", sort(unique(B0_conditions)))))

final_results


```


# export simulation results to .csv file
```{r}

write_csv(final_results, file = "../output/analyses/supplement/browser_bistability-all.csv")

```



# plotting all the browser scenarios together!
```{r}


browser_bistability <- final_results


# Define the custom color scale
custom_colors <- colorRampPalette(c("#FCF0D1", "#FAE8B7", "#FAC8AF", "#F9A7A6", "#F9879E", "#F86696", "#F8468D", "#f20089", "#e500a4", "#db00b6", "#b5179e", "#7209b7"))


# custom_colors <- colorRampPalette(c("#FCF0D1", "#FBD9CC", "#FBC3C7", "#FAACC2", "#FA96BD", "#F97FB7", "#F969B2", "#F852AD", "#F83CA8", "#F725A3"))


pdf("../output/figures/Fig_S10_v1.pdf",width=5,height=9)

# quartz()
ggplot(browser_bistability, aes(Fishing_Pressure, Initial_Coral)) +
  geom_tile(aes(fill = Final_Coral)) +
  theme_classic(base_size=14,base_family = "Times") + 
  theme(axis.title=element_text(size=16,face="bold")) +
  labs(fill = "Final\nCoral\nCover") +
  scale_fill_gradientn(colors = custom_colors(50), limits=c(0,0.8)) +
  scale_colour_gradientn(colors = custom_colors(50), limits=c(0,0.8)) +
  # scale_fill_viridis(option = "magma",
  #                    begin = 0.2,
  #                    end = 0.9,
  #                    limits=c(0,0.8)) +
  # scale_colour_viridis(option = "viridis",limits=c(0,0.8)) +
    scale_x_continuous("Fishing Pressure",expand = c(0, 0), breaks = c(0,0.25,0.5,0.75,1),
                         labels = c(0,0.25,0.5,0.75,1)) +
    scale_y_continuous("Initial Coral Cover", expand = c(0, 0), breaks = c(0,0.2,0.4,0.6,0.8),
                         labels = c(0,0.2,0.4,0.6,0.8)) +
  facet_wrap(~Id,nrow = 4, ncol = 2) +
  theme(strip.text.x = element_text(size = 11))

# dev.off()

```


